name: Lint Codebase

on:
  push:
    branches: []
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '**/package.json'
      - '**/package-lock.json'
      - '**/.eslintrc*'
      - '**/.prettierrc*'
      - '**/*.{js,jsx,ts,tsx,json}'
jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Root Dependencies
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint Frontend
        working-directory: ./frontend
        run: |
          npx eslint "**/*.{js,jsx,ts,tsx}" --max-warnings=0
          npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,scss,md}"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            frontend/node_modules
            backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
